SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT USER_INFO.USER_ID) AS USERS
FROM USER_INFO 
JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID 
WHERE USER_INFO.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_INFO.GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_INFO.GENDER;
