-- 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 --
-- 즉, 기준 테이블을 입양 보낸 동물의 정보를 담은 테이블 ANIMAL_OUTS--
-- 만약 기록이 없다면 JOIN 후 보호소에 들어온 동물 정보 테이블의 INTAKE_CONDITION이 NULL이 된다.--
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS
LEFT OUTER JOIN ANIMAL_INS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE INTAKE_CONDITION IS NULL
ORDER BY ANIMAL_ID, NAME;
