-- 서브 쿼리로 음식종류별로(그룹화) 가장 즐겨찾기가 많은 식당을 뽑는다.
-- 위에서 뽑은 행들을 WHERE문으로 찾고(SELECT 문의 결과인 734, 230, 102의 FAVORITES값을 가진 컬럼에서) 
-- GROUP BY로 음식 종류 별로 그룹화, 정렬
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE FAVORITES IN(SELECT MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;
